[package]
name = "biopass"
version = "0.1.0"
description = "A Tauri App"
authors = ["you"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
# The `_lib` suffix may seem redundant but it is necessary
# to make the lib name unique and wouldn't conflict with the bin name.
# This seems to be only an issue on Windows, see https://github.com/rust-lang/cargo/issues/8519
name = "biopass_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }
pkg-config = "0.3"

[dependencies]
tauri = { version = "2", features = ["protocol-asset"] }
tauri-plugin-opener = "2"
tauri-plugin-fs = "2"
serde = { version = "1", features = ["derive"] }

serde_json = "1"
serde_yml = "0.0.12"
directories = "5"
base64 = "0.22"
webkit2gtk = "2.0.1"

gtk = "0.18.2"
tauri-plugin-dialog = "2"
tokio = { version = "1.36.0", features = ["full"] }

[dev-dependencies]
tempfile = "3"
